remote_theme: ages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Quikin
description: A personal notebook regarding all things application development; dev ops, clean coding, cloud native, soft skills, and more.


